In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [54]:
df = pd.read_csv('minesafe_100_rows_10_features.csv')
df

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min,priority
0,Water Increase,Moderate,11,2,25,10,34.5,Degraded,25.6,9,MEDIUM
1,Gas Leak,Moderate,14,4,35,4,8.5,Normal,23.3,33,MEDIUM
2,Electrical Fault,Serious,30,1,19,17,46.4,Normal,17.5,5,HIGH
3,Conveyor Accident,Critical,20,3,8,18,68.0,Normal,27.7,151,CRITICAL
4,Electrical Fault,Moderate,20,5,3,6,65.5,Normal,7.8,163,MEDIUM
...,...,...,...,...,...,...,...,...,...,...,...
95,Conveyor Accident,Serious,29,2,6,5,3.9,Normal,33.6,103,HIGH
96,Conveyor Accident,Minor,13,0,13,11,76.5,Degraded,8.9,116,LOW
97,Water Increase,Serious,14,4,37,6,26.5,Degraded,6.5,165,HIGH
98,Roof Fall,Serious,25,5,11,2,25.9,Degraded,32.4,147,HIGH
99,Fire,Serious,4,4,41,3,21.5,Normal,11.4,163,HIGH

In [55]:
df.isnull().sum()

incident_type                0
severity                     0
workers_at_risk              0
injured_count                0
hazard_intensity             0
workers_in_danger_zone       0
nearest_worker_distance_m    0
communication_status         0
rescue_response_time_min     0
time_since_incident_min      0
priority                     0
dtype: int64

In [56]:
df['incident_type'].unique()

<ArrowStringArray>
[   'Water Increase',          'Gas Leak',  'Electrical Fault',
 'Conveyor Accident',              'Fire',         'Roof Fall']
Length: 6, dtype: str

In [57]:
df['incident_type'] = df['incident_type'].replace({'Water Ingress': 'Water Increase'})
df.to_csv("minesafe_100_rows_10_features.csv", index=False)

In [58]:
df

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min,priority
0,Water Increase,Moderate,11,2,25,10,34.5,Degraded,25.6,9,MEDIUM
1,Gas Leak,Moderate,14,4,35,4,8.5,Normal,23.3,33,MEDIUM
2,Electrical Fault,Serious,30,1,19,17,46.4,Normal,17.5,5,HIGH
3,Conveyor Accident,Critical,20,3,8,18,68.0,Normal,27.7,151,CRITICAL
4,Electrical Fault,Moderate,20,5,3,6,65.5,Normal,7.8,163,MEDIUM
...,...,...,...,...,...,...,...,...,...,...,...
95,Conveyor Accident,Serious,29,2,6,5,3.9,Normal,33.6,103,HIGH
96,Conveyor Accident,Minor,13,0,13,11,76.5,Degraded,8.9,116,LOW
97,Water Increase,Serious,14,4,37,6,26.5,Degraded,6.5,165,HIGH
98,Roof Fall,Serious,25,5,11,2,25.9,Degraded,32.4,147,HIGH
99,Fire,Serious,4,4,41,3,21.5,Normal,11.4,163,HIGH

In [59]:
df['severity'].unique()

<ArrowStringArray>
['Moderate', 'Serious', 'Critical', 'Minor']
Length: 4, dtype: str

In [60]:
df['communication_status'].unique()

<ArrowStringArray>
['Degraded', 'Normal', 'Lost']
Length: 3, dtype: str

In [61]:
le = LabelEncoder()
df['incident_type']=le.fit_transform(df['incident_type'])
df

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min,priority
0,5,Moderate,11,2,25,10,34.5,Degraded,25.6,9,MEDIUM
1,3,Moderate,14,4,35,4,8.5,Normal,23.3,33,MEDIUM
2,1,Serious,30,1,19,17,46.4,Normal,17.5,5,HIGH
3,0,Critical,20,3,8,18,68.0,Normal,27.7,151,CRITICAL
4,1,Moderate,20,5,3,6,65.5,Normal,7.8,163,MEDIUM
...,...,...,...,...,...,...,...,...,...,...,...
95,0,Serious,29,2,6,5,3.9,Normal,33.6,103,HIGH
96,0,Minor,13,0,13,11,76.5,Degraded,8.9,116,LOW
97,5,Serious,14,4,37,6,26.5,Degraded,6.5,165,HIGH
98,4,Serious,25,5,11,2,25.9,Degraded,32.4,147,HIGH
99,2,Serious,4,4,41,3,21.5,Normal,11.4,163,HIGH

In [62]:
ord = OrdinalEncoder(categories=[['Normal','Degraded','Lost']])
df['communication_status']=ord.fit_transform(df[['communication_status']])
df

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min,priority
0,5,Moderate,11,2,25,10,34.5,1.0,25.6,9,MEDIUM
1,3,Moderate,14,4,35,4,8.5,0.0,23.3,33,MEDIUM
2,1,Serious,30,1,19,17,46.4,0.0,17.5,5,HIGH
3,0,Critical,20,3,8,18,68.0,0.0,27.7,151,CRITICAL
4,1,Moderate,20,5,3,6,65.5,0.0,7.8,163,MEDIUM
...,...,...,...,...,...,...,...,...,...,...,...
95,0,Serious,29,2,6,5,3.9,0.0,33.6,103,HIGH
96,0,Minor,13,0,13,11,76.5,1.0,8.9,116,LOW
97,5,Serious,14,4,37,6,26.5,1.0,6.5,165,HIGH
98,4,Serious,25,5,11,2,25.9,1.0,32.4,147,HIGH
99,2,Serious,4,4,41,3,21.5,0.0,11.4,163,HIGH

In [63]:
ord = OrdinalEncoder(categories=[['Minor', 'Moderate', 'Serious', 'Critical']])
df['severity']=ord.fit_transform(df[['severity']])
df

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min,priority
0,5,1.0,11,2,25,10,34.5,1.0,25.6,9,MEDIUM
1,3,1.0,14,4,35,4,8.5,0.0,23.3,33,MEDIUM
2,1,2.0,30,1,19,17,46.4,0.0,17.5,5,HIGH
3,0,3.0,20,3,8,18,68.0,0.0,27.7,151,CRITICAL
4,1,1.0,20,5,3,6,65.5,0.0,7.8,163,MEDIUM
...,...,...,...,...,...,...,...,...,...,...,...
95,0,2.0,29,2,6,5,3.9,0.0,33.6,103,HIGH
96,0,0.0,13,0,13,11,76.5,1.0,8.9,116,LOW
97,5,2.0,14,4,37,6,26.5,1.0,6.5,165,HIGH
98,4,2.0,25,5,11,2,25.9,1.0,32.4,147,HIGH
99,2,2.0,4,4,41,3,21.5,0.0,11.4,163,HIGH

In [64]:
df['priority'].unique()

<ArrowStringArray>
['MEDIUM', 'HIGH', 'CRITICAL', 'LOW']
Length: 4, dtype: str

In [65]:
ord = OrdinalEncoder(categories=[['LOW','MEDIUM', 'HIGH', 'CRITICAL']])
df['priority']=ord.fit_transform(df[['priority']])
df

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min,priority
0,5,1.0,11,2,25,10,34.5,1.0,25.6,9,1.0
1,3,1.0,14,4,35,4,8.5,0.0,23.3,33,1.0
2,1,2.0,30,1,19,17,46.4,0.0,17.5,5,2.0
3,0,3.0,20,3,8,18,68.0,0.0,27.7,151,3.0
4,1,1.0,20,5,3,6,65.5,0.0,7.8,163,1.0
...,...,...,...,...,...,...,...,...,...,...,...
95,0,2.0,29,2,6,5,3.9,0.0,33.6,103,2.0
96,0,0.0,13,0,13,11,76.5,1.0,8.9,116,0.0
97,5,2.0,14,4,37,6,26.5,1.0,6.5,165,2.0
98,4,2.0,25,5,11,2,25.9,1.0,32.4,147,2.0
99,2,2.0,4,4,41,3,21.5,0.0,11.4,163,2.0

In [66]:
x= df.drop(['priority'],axis=1)
x

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min
0,5,1.0,11,2,25,10,34.5,1.0,25.6,9
1,3,1.0,14,4,35,4,8.5,0.0,23.3,33
2,1,2.0,30,1,19,17,46.4,0.0,17.5,5
3,0,3.0,20,3,8,18,68.0,0.0,27.7,151
4,1,1.0,20,5,3,6,65.5,0.0,7.8,163
...,...,...,...,...,...,...,...,...,...,...
95,0,2.0,29,2,6,5,3.9,0.0,33.6,103
96,0,0.0,13,0,13,11,76.5,1.0,8.9,116
97,5,2.0,14,4,37,6,26.5,1.0,6.5,165
98,4,2.0,25,5,11,2,25.9,1.0,32.4,147
99,2,2.0,4,4,41,3,21.5,0.0,11.4,163

In [67]:
y = df[['priority']]
y

    priority
0        1.0
1        1.0
2        2.0
3        3.0
4        1.0
..       ...
95       2.0
96       0.0
97       2.0
98       2.0
99       2.0

[100 rows x 1 columns]

In [68]:
Scaler=StandardScaler()
df1=Scaler.fit_transform(x)
df1

array([[ 1.49986865, -0.27836557, -1.04617232, -0.2055777 ,  0.21148291,
         0.32361932, -0.2612692 ,  0.90833751, -0.38330558, -1.51550369],
       [ 0.34166892, -0.27836557, -0.73106017,  1.12073007,  1.06768903,
        -0.67726518, -1.34814908, -0.63121759, -0.53421329, -1.04079619],
       [-0.81653081,  0.79227124,  0.94953792, -0.86873159, -0.30224076,
         1.49131791,  0.23618736, -0.63121759, -0.91476316, -1.59462161],
       [-1.39563067,  1.86290805, -0.10083589,  0.45757618, -1.24406749,
         1.658132  ,  1.13913372, -0.63121759, -0.24552028,  1.29318235],
       [-0.81653081, -0.27836557, -0.10083589,  1.78388395, -1.67217055,
        -0.34363701,  1.03462604, -0.63121759, -1.55120002,  1.5305361 ],
       [ 0.34166892,  0.79227124,  0.42435102, -1.53188548,  0.21148291,
        -1.01089335, -1.25200201, -0.63121759,  1.84094282, -0.26939651],
       [ 1.49986865, -0.27836557,  0.21427626, -1.53188548,  0.63958597,
         1.49131791,  1.49445983,  0.90833751,  0.88300693,  1.25362339],
       [ 1.49986865, -0.27836557, -0.62602279, -0.2055777 , -0.13099954,
         1.15768974, -0.8966759 , -0.63121759, -1.61025086,  1.72833089],
       [ 0.34166892,  0.79227124,  0.73946316,  1.78388395,  1.41017148,
         1.658132  , -0.92175774,  2.44789261, -0.42267281, -0.52652974],
       [-1.39563067, -1.34900238, -1.88647136, -1.53188548, -1.07282627,
        -1.34452152, -0.50790733,  0.90833751,  0.50901826,  1.60965402],
       [-0.23743094, -0.27836557,  0.73946316, -0.86873159,  1.49579209,
         1.15768974, -0.51626794, -0.63121759, -0.73761063,  1.01626964],
       [-0.81653081,  0.79227124,  0.73946316,  1.78388395, -0.81596443,
         1.15768974, -1.05134726, -0.63121759, -0.79666148, -1.04079619],
       [ 0.92076878, -1.34900238, -0.31091065, -1.53188548, -0.21662015,
         0.65724749,  0.61659531, -0.63121759,  1.14545512,  0.16575204],
       [ 0.92076878,  0.79227124, -0.52098541,  1.78388395, -0.38786137,
         0.32361932, -0.21528582,  0.90833751,  1.38165849, -1.45616526],
       [-0.81653081, -0.27836557,  1.05457531, -0.86873159, -0.81596443,
        -0.5104511 ,  1.5362629 ,  0.90833751,  0.79115006, -0.32873494],
       [-0.81653081,  0.79227124,  1.15961269, -0.2055777 , -0.04537892,
         1.15768974, -0.62077562, -0.63121759,  0.54838549,  1.64921297],
       [-0.23743094, -1.34900238,  1.26465007,  0.45757618,  0.8108272 ,
         1.49131791,  0.47864518, -0.63121759, -1.32155785,  1.21406443],
       [ 0.34166892, -0.27836557,  0.10923888,  0.45757618,  1.23893026,
         0.49043341, -0.76708637, -0.63121759, -1.16408894,  1.15472599],
       [-1.39563067, -1.34900238, -1.36128446, -0.2055777 , -0.13099954,
        -0.84407927, -0.00627046,  0.90833751,  0.5615079 ,  0.1064136 ],
       [-0.23743094,  1.86290805, -0.94113493,  1.78388395,  0.46834475,
        -0.01000885, -1.57806597, -0.63121759, -0.5538969 ,  0.56134162],
       [ 1.49986865, -0.27836557,  1.05457531,  1.78388395,  0.38272414,
         0.82406158,  0.03553261,  0.90833751,  0.53526308, -0.28917599],
       [-1.39563067,  1.86290805, -0.20587327,  0.45757618, -0.04537892,
        -1.01089335,  0.10241753, -0.63121759, -1.05910966, -1.45616526],
       [-1.39563067,  0.79227124, -0.73106017, -0.86873159, -0.21662015,
        -0.5104511 ,  1.03880634, -0.63121759,  1.25043439, -0.38807338],
       [-0.81653081, -0.27836557, -0.31091065,  1.78388395, -1.15844688,
         0.65724749,  1.01790481, -0.63121759,  1.37509728, -0.01226328],
       [ 0.34166892, -1.34900238,  0.0042015 , -0.2055777 ,  1.75265393,
        -0.5104511 ,  1.56134475, -0.63121759, -1.42653713,  0.1064136 ],
       [-0.81653081,  1.86290805,  1.47472483, -1.53188548, -0.81596443,
         0.82406158,  0.95938051,  0.90833751,  0.22032525,  0.54156214],
       [-0.23743094, -1.34900238,  1.36968745, -0.86873159,  2.18075699,
        -1.17770743, -1.54880382, -0.63121759, -0.20615305,  0.02729568],
       [ 1.49986865,  0.79227124,  0.42435102,  1.12073007, -0.21662015,
        -1.17770743, -1.03044573, -0.63121759, -0.74417184, -0.52652974],
       [-0.81653081, -1.34900238, -0.73106017, -0.86873159, -1.50092933,
        -1.34452152,  1.25618232, -0.63121759,  1.46039294, -0.3682939 ],
       [ 0.92076878, -1.34900238, -0.10083589, -0.86873159,  0.21148291,
         0.49043341, -1.56552505,  2.44789261,  1.10608789, -0.86278088],
       [-0.23743094,  1.86290805,  0.73946316,  1.12073007,  1.66703332,
         1.15768974, -0.38667842, -0.63121759, -0.02900052, -1.15947307],
       [ 0.92076878,  0.79227124, -0.10083589,  0.45757618,  0.21148291,
        -0.67726518,  0.38249811, -0.63121759,  0.12190718,  0.66023901],
       [ 0.92076878, -0.27836557,  0.31931364,  1.12073007, -0.73034382,
         0.32361932, -0.59987409, -0.63121759, -0.46860124,  0.14597256],
       [ 0.34166892, -1.34900238, -1.25624708,  0.45757618, -0.98720566,
        -0.34363701,  1.10987157,  0.90833751, -0.94100798,  0.99649016],
       [ 1.49986865, -1.34900238,  0.73946316, -0.2055777 ,  0.04024169,
         0.49043341, -1.5362629 , -0.63121759,  1.61130065,  1.17450547],
       [ 0.92076878, -0.27836557, -1.78143398, -1.53188548, -0.81596443,
        -0.84407927, -0.3783178 ,  2.44789261, -0.8360287 ,  0.28442891],
       [-0.23743094, -0.27836557, -1.1512097 , -0.2055777 ,  0.63958597,
        -1.17770743,  1.46519768, -0.63121759,  1.56537222, -1.47594474],
       [-0.23743094,  0.79227124,  0.84450054,  0.45757618,  1.92389515,
         1.658132  , -0.93847897,  0.90833751, -0.22583667, -0.62542713],
       [-0.81653081,  0.79227124,  1.36968745, -1.53188548, -1.58654994,
         0.15680524,  1.62404935, -0.63121759,  0.90269054, -0.98145776],
       [ 1.49986865, -0.27836557, -1.36128446,  0.45757618,  0.1258623 ,
        -0.84407927,  0.30307227, -0.63121759, -1.36748628,  1.45141818],
       [-1.39563067, -0.27836557, -1.78143398, -1.53188548, -0.38786137,
        -1.34452152,  0.48282548, -0.63121759, -1.64961809,  0.18553151],
       [ 0.34166892,  0.79227124, -0.31091065, -0.86873159,  0.04024169,
         0.99087566, -0.34069504,  0.90833751, -0.18646944, -0.58586817],
       [ 0.34166892, -0.27836557, -1.78143398, -0.2055777 ,  0.72520658,
        -0.84407927, -0.55807101, -0.63121759,  1.43414812,  0.4822237 ],
       [-1.39563067,  0.79227124,  0.73946316, -0.2055777 , -0.98720566,
        -0.01000885, -1.17675648, -0.63121759,  0.92237416, -1.10013463],
       [ 0.34166892,  0.79227124,  0.84450054,  0.45757618,  1.41017148,
        -1.17770743, -1.0137245 , -0.63121759,  1.33573005,  1.78766933],
       [-0.23743094, -0.27836557,  0.5293884 , -0.86873159,  1.32455087,
         0.32361932,  0.35323596,  2.44789261,  1.5391274 , -1.53528317],
       [-0.81653081,  0.79227124, -0.41594803, -0.86873159, -0.47348198,
         1.49131791,  1.21855955, -0.63121759, -0.44235642, -1.25837047],
       [ 0.34166892, -1.34900238, -1.78143398,  0.45757618, -0.21662015,
        -1.34452152,  1.4192143 ,  0.90833751,  0.21376405, -1.59462161],
       [-0.23743094,  0.79227124,  0.21427626, -0.2055777 ,  1.66703332,
        -1.34452152,  1.1307731 ,  0.90833751,  0.0103667 , -1.49572422],
       [-0.81653081, -0.27836557,  0.42435102,  0.45757618, -0.98720566,
         1.15768974,  1.38159153, -0.63121759,  0.88300693,  1.03604912],
       [ 0.92076878, -0.27836557,  1.47472483, -0.86873159, -0.5591026 ,
         1.49131791, -1.09315034,  0.90833751,  0.60087513, -0.19027859],
       [-1.39563067, -1.34900238,  1.36968745, -0.86873159, -0.98720566,
         1.49131791, -0.62077562, -0.63121759,  0.73209922, -0.13094015],
       [-1.39563067, -0.27836557, -0.31091065,  1.12073007, -0.90158505,
         1.15768974,  0.55389071,  2.44789261, -0.34393835, -0.28917599],
       [ 0.34166892, -0.27836557,  1.15961269, -0.2055777 ,  0.89644781,
        -0.34363701, -0.24872828,  2.44789261, -0.26520389, -0.34851442],
       [-1.39563067,  1.86290805,  0.42435102, -0.2055777 , -1.07282627,
         0.82406158,  0.39921934, -0.63121759,  1.01423102, -1.23859099],
       [-0.81653081, -0.27836557,  1.26465007, -0.2055777 , -0.5591026 ,
         0.49043341, -0.19438429, -0.63121759,  0.29905971, -0.74410401],
       [-1.39563067,  1.86290805, -1.78143398, -0.86873159, -0.30224076,
        -1.01089335,  0.33651473, -0.63121759, -1.35436387, -1.49572422],
       [-0.23743094, -0.27836557,  0.84450054, -0.2055777 ,  1.75265393,
         1.32450383,  0.86741375, -0.63121759, -1.31499665, -1.45616526],
       [-1.39563067, -1.34900238,  0.84450054, -0.2055777 , -0.38786137,
        -1.34452152,  0.07315538, -0.63121759,  0.25969248, -0.28917599],
       [ 0.34166892, -1.34900238,  0.42435102, -0.86873159,  0.04024169,
        -0.01000885,  1.14331402, -0.63121759, -1.61025086,  0.02729568],
       [ 0.92076878, -1.34900238, -0.94113493,  0.45757618, -0.21662015,
        -0.84407927, -0.58733316, -0.63121759, -1.15752773, -0.90233984],
       [ 1.49986865,  0.79227124,  1.26465007, -0.2055777 , -0.04537892,
         0.65724749, -1.02208511,  0.90833751, -0.36362196,  0.83825433],
       [ 0.92076878, -1.34900238,  0.94953792,  1.12073007, -0.47348198,
         1.658132  , -0.01463108,  0.90833751, -0.56701931, -0.40785286],
       [-0.81653081, -0.27836557,  0.73946316, -0.86873159, -0.47348198,
        -0.17682293, -1.13913372,  2.44789261,  1.52600499, -1.51550369],
       [-0.23743094,  0.79227124,  0.63442578,  0.45757618,  2.35199821,
        -1.01089335,  0.97192143, -0.63121759,  1.86718763,  0.62068006],
       [ 0.34166892, -0.27836557,  0.84450054, -0.2055777 , -0.04537892,
        -0.01000885, -1.54880382,  0.90833751,  1.18482235, -0.05182224],
       [ 0.92076878, -1.34900238,  1.05457531, -0.2055777 ,  0.63958597,
         0.32361932,  1.58224628, -0.63121759, -1.46590435,  0.85803381],
       [-0.23743094, -0.27836557, -1.88647136, -0.2055777 ,  2.43761883,
        -1.34452152,  1.21855955, -0.63121759, -0.58670292, -0.52652974],
       [ 0.92076878, -0.27836557,  0.0042015 ,  1.78388395, -0.30224076,
         1.15768974,  0.85487283, -0.63121759,  0.4171614 , -0.32873494],
       [ 0.34166892,  0.79227124, -1.36128446,  1.12073007, -0.21662015,
        -1.34452152,  1.19347771, -0.63121759,  0.81739488, -1.25837047],
       [ 0.92076878,  1.86290805,  0.21427626,  0.45757618, -0.21662015,
        -0.84407927, -1.57806597,  0.90833751, -0.31113233, -1.33748838],
       [-1.39563067,  0.79227124,  1.36968745,  0.45757618, -1.67217055,
        -0.5104511 ,  1.45683706, -0.63121759,  0.62711995,  0.5811211 ],
       [ 0.92076878, -0.27836557, -1.6763966 ,  1.12073007, -0.47348198,
        -0.5104511 ,  0.45356333, -0.63121759, -1.30843544,  0.18553151],
       [-1.39563067, -0.27836557,  1.36968745, -1.53188548, -0.81596443,
         1.658132  , -0.06897507, -0.63121759,  1.17826114,  1.70855141],
       [ 0.34166892, -0.27836557, -0.20587327,  1.12073007, -0.73034382,
         1.49131791, -0.34905565, -0.63121759, -0.42267281,  0.52178266],
       [ 0.34166892, -0.27836557, -0.94113493,  1.12073007,  0.29710352,
        -1.34452152, -1.17675648, -0.63121759, -0.58014172, -0.17049911],
       [ 0.34166892, -0.27836557,  0.63442578, -0.2055777 , -0.04537892,
         0.32361932, -1.57806597,  0.90833751,  1.03391464,  1.35252079],
       [ 1.49986865, -0.27836557, -1.04617232,  1.12073007,  0.89644781,
        -0.17682293, -1.45265676, -0.63121759,  0.74522163, -0.78366296],
       [-1.39563067,  1.86290805,  0.0042015 , -0.2055777 , -1.15844688,
        -1.34452152,  0.59151347, -0.63121759,  0.12190718, -0.09138119],
       [-0.23743094,  0.79227124,  1.47472483,  0.45757618,  0.8108272 ,
        -0.34363701, -0.87577436, -0.63121759, -0.46860124, -0.82322192],
       [-0.23743094, -0.27836557, -1.25624708, -0.86873159,  2.18075699,
        -0.84407927, -0.14004029,  0.90833751, -0.1339798 , -0.13094015],
       [-1.39563067, -1.34900238,  0.94953792, -1.53188548, -0.13099954,
         0.99087566,  1.32724754, -0.63121759,  1.28980162,  0.68001849],
       [ 1.49986865,  1.86290805,  0.31931364, -0.86873159,  0.21148291,
        -1.17770743,  1.60732812, -0.63121759, -1.48558797, -0.86278088],
       [-1.39563067, -0.27836557,  0.21427626, -1.53188548, -0.81596443,
        -1.01089335,  0.62913624,  2.44789261, -0.10117378,  1.51075662],
       [ 0.92076878, -1.34900238, -0.94113493,  0.45757618, -0.73034382,
        -0.67726518, -1.19347771, -0.63121759,  1.86062643, -0.56608869],
       [ 0.92076878, -1.34900238,  1.05457531,  0.45757618, -0.81596443,
         1.32450383, -0.62077562, -0.63121759, -0.10773498, -0.62542713],
       [ 1.49986865, -0.27836557,  0.10923888, -0.2055777 , -0.47348198,
         1.49131791, -1.41085369, -0.63121759, -1.50527158, -1.19903203],
       [-1.39563067, -1.34900238,  1.47472483,  0.45757618, -1.75779117,
        -1.17770743,  0.5497104 , -0.63121759, -1.31499665,  0.02729568],
       [ 1.49986865, -0.27836557, -0.31091065, -0.86873159, -0.64472321,
         1.15768974, -0.36159657, -0.63121759,  0.30562092,  1.09538756],
       [-1.39563067,  0.79227124,  0.63442578, -0.86873159, -0.47348198,
         0.15680524,  1.63659027, -0.63121759, -0.15366341, -0.58586817],
       [-0.23743094,  0.79227124, -0.31091065, -0.2055777 ,  1.23893026,
        -1.17770743,  0.32397381, -0.63121759, -1.1115993 ,  0.12619308],
       [ 1.49986865,  1.86290805, -1.6763966 , -1.53188548, -0.47348198,
        -1.34452152, -0.54134978, -0.63121759,  0.46308983,  0.85803381],
       [ 0.34166892, -1.34900238, -1.46632184,  1.78388395, -0.73034382,
        -0.67726518,  0.75872576,  2.44789261,  0.15471321,  1.82722829],
       [ 1.49986865, -0.27836557, -1.25624708,  1.12073007, -0.30224076,
        -0.34363701,  0.34069504, -0.63121759,  1.53256619, -0.22983755],
       [ 0.34166892, -0.27836557, -0.73106017, -0.86873159,  1.75265393,
        -0.34363701, -1.34814908, -0.63121759, -0.10117378,  1.82722829],
       [-1.39563067,  0.79227124,  0.84450054, -0.2055777 , -1.41530872,
        -0.5104511 , -1.54044321, -0.63121759,  0.1415908 ,  0.34376735],
       [-1.39563067, -1.34900238, -0.83609755, -1.53188548, -0.81596443,
         0.49043341,  1.49445983,  0.90833751, -1.47902676,  0.60090058],
       [ 1.49986865,  0.79227124, -0.73106017,  1.12073007,  1.23893026,
        -0.34363701, -0.59569378,  0.90833751, -1.63649568,  1.57009506],
       [ 0.92076878,  0.79227124,  0.42435102,  1.78388395, -0.98720566,
        -1.01089335, -0.62077562,  0.90833751,  0.06285634,  1.21406443],
       [-0.23743094,  0.79227124, -1.78143398,  1.12073007,  1.58141271,
        -0.84407927, -0.80470914, -0.63121759, -1.31499665,  1.5305361 ]])

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [71]:
x_train_Scaled=Scaler.fit_transform(x_train)
x_test_Scaled=Scaler.fit_transform(x_test)

In [72]:
x_train

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min
55,1,1.0,33,2,16,11,36.1,0.0,36.0,48
88,5,1.0,18,1,15,15,32.1,0.0,36.1,141
26,2,0.0,34,1,48,1,3.7,0.0,28.3,87
42,3,1.0,4,2,31,3,27.4,0.0,53.3,110
69,3,2.0,8,4,20,0,69.3,0.0,43.9,22
...,...,...,...,...,...,...,...,...,...,...
60,4,0.0,12,3,20,3,26.7,0.0,13.8,40
71,0,2.0,34,3,3,5,75.6,0.0,41.0,115
14,1,1.0,31,1,13,5,77.5,1.0,43.5,69
92,3,0.0,7,5,14,4,58.9,2.0,33.8,178
51,0,0.0,34,1,11,17,25.9,0.0,42.6,79

In [73]:
x_test

,incident_type,severity,workers_at_risk,injured_count,hazard_intensity,workers_in_danger_zone,nearest_worker_distance_m,communication_status,rescue_response_time_min,time_since_incident_min
83,0,1.0,23,0,13,2,55.8,2.0,29.9,162
53,3,1.0,32,2,33,6,34.8,2.0,27.4,68
70,4,3.0,23,3,20,3,3.0,1.0,26.7,18
45,2,1.0,26,1,38,10,49.2,2.0,54.9,8
44,3,2.0,29,3,39,1,16.5,0.0,51.8,176
39,5,1.0,8,3,24,3,48.0,0.0,10.6,159
22,0,2.0,14,1,20,5,65.6,0.0,50.5,66
80,2,1.0,9,1,48,3,37.4,1.0,29.4,79
10,2,1.0,28,1,40,15,28.4,0.0,20.2,137
0,5,1.0,11,2,25,10,34.5,1.0,25.6,9
18,0,0.0,8,2,21,3,40.6,1.0,40.0,91
30,2,3.0,28,4,42,15,31.5,0.0,31.0,27
73,0,1.0,34,0,13,18,39.1,0.0,49.4,172
33,3,0.0,9,3,11,6,67.3,1.0,17.1,136
90,2,2.0,18,2,37,1,48.5,0.0,14.5,92
4,1,1.0,20,5,3,6,65.5,0.0,7.8,163
76,3,1.0,27,2,22,10,3.0,1.0,47.2,154
77,5,1.0,11,4,33,7,6.0,0.0,42.8,46
12,4,0.0,18,0,20,12,55.5,0.0,48.9,94
31,4,2.0,20,3,25,4,49.9,0.0,33.3,119

In [74]:
from sklearn.svm import SVC

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
svm_model=SVC(kernel='linear')

In [77]:
svm_model.fit(x_train_Scaled,y_train)

c:\Users\sayooj ramkumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(kernel='linear')

In [78]:
svm_prediction=svm_model.predict(x_test_Scaled)

In [79]:
accuracy_score(y_test,svm_prediction)

0.9

In [80]:
joblib.dump(svm_model,"minesafe_priority_model.pkl")

['minesafe_priority_model.pkl']